### ISSUE TITLE
Plugin name already registered: _cov

### ISSUE THREAD

**Issue by mtelka** [jaraco/pytest-enabler#8]
It looks like `pluggy==1.2.0`, `pytest==7.4.0`, `pytest-enabler==2.2.0`, and `pytest-cov==4.1.0` does not work together:
```
$ pytest --cov
Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.9/vendor-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 133, in _multicall
    teardown[0].send(outcome)
  File "/usr/lib/python3.9/vendor-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.9/vendor-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1327, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3.9/vendor-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.9/vendor-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/vendor-packages/pytest_enabler/__init__.py", line 50, in pytest_load_initial_conftests
    _pytest_cov_check(enabled, early_config, parser, args)
  File "/usr/lib/python3.9/vendor-packages/pytest_enabler/__init__.py", line 84, in _pytest_cov_check
    pytest_cov.plugin.pytest_load_initial_conftests(early_config, parser, args)
  File "/usr/lib/python3.9/vendor-packages/pytest_cov/plugin.py", line 153, in pytest_load_initial_conftests
    early_config.pluginmanager.register(plugin, '_cov')
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 488, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 129, in register
    raise ValueError(
ValueError: Plugin name already registered: _cov=<pytest_cov.plugin.CovPlugin object at 0x7fffade11f70>
...
```
When I uninstall `pytest-enabler` the problem is gone.

**Comment by jaraco** [comment]
Starting with pytest-enabler 2.2, it now includes a [default config](https://github.com/jaraco/pytest-enabler/blob/main/pytest_enabler/default.toml), which means that if `pytest-cov` is installed, unless `[tool.pytest-enabler.cov]` is present in pyproject.toml, `pytest-enabler` will inject `--cov` to the options to `pytest` implicitly. In retrospect, maybe that release should have been flagged as backward-incompatible, but I hadn't recognized this use-case.

Your options include:

- uninstall `pytest-enabler`
- pin to `pytest-enabler<2.2`
- disable `pytest-enabler` with `-p no:enabler`
- Create a blank `[tool.pytest-enabler.cov]`
- Stop passing `--cov` explicitly (my recommendation)

Does that help?

**Comment by jaraco** [comment]
Hmm... I assumed that what was happening was `--cov` was getting added twice, but I tried installing `pytest` and `pytest-cov` then invoked `pytest --cov --cov` and I couldn't replicate the failure, so maybe there's something more complicated going on.

**Comment by jaraco** [comment]
Revisiting the traceback and looking at the [special handling for pytest-cov](https://github.com/jaraco/pytest-enabler/blob/30c49c07e495e12b8f74c6860c9783137a8917a9/pytest_enabler/__init__.py#L68-L84), I think it may be possible that `enabler` should back-off when the plugin is already enabled by an explicit `--cov` in the command-line.
